"""
Texture manifest cleanup operator.

Deletes the _manifests folder under the project RSC/Textures directory.
This removes JSON reports and hash index files generated by texture scan/adopt.
"""

from __future__ import annotations

from pathlib import Path
import shutil
from typing import Optional

import bpy
from bpy.types import Operator

from ..core.texture_workspace import deduce_texture_project_workspace, resolve_texture_root


def _state_local_mode(context) -> bool:
    st = getattr(getattr(context, "window_manager", None), "lime_pipeline", None)
    return bool(getattr(st, "use_local_project", False)) if st is not None else False


def _deduce_project_root(context) -> tuple[Optional[Path], bool]:
    st = getattr(getattr(context, "window_manager", None), "lime_pipeline", None)
    raw_root = (getattr(st, "project_root", "") or "").strip() if st is not None else ""
    blend_path = (getattr(bpy.data, "filepath", "") or "").strip()
    root, local_mode = deduce_texture_project_workspace(
        state_project_root=raw_root,
        use_local_project=_state_local_mode(context),
        blend_path=blend_path,
    )
    return root, local_mode


def _blend_dir() -> Path:
    blend_path = (getattr(bpy.data, "filepath", "") or "").strip()
    if blend_path:
        try:
            return Path(blend_path).resolve().parent
        except Exception:
            return Path(blend_path).parent
    try:
        return Path(bpy.path.abspath("//")).resolve()
    except Exception:
        return Path.cwd()


def _resolve_texture_root(project_root: Optional[Path], *, local_mode: bool) -> Path:
    return resolve_texture_root(project_root, local_mode=local_mode, blend_dir=_blend_dir())


class LIME_OT_texture_manifest_cleanup(Operator):
    bl_idname = "lime.texture_manifest_cleanup"
    bl_label = "Delete Texture Manifests"
    bl_description = "Delete the _manifests folder under RSC/Textures"
    bl_options = {"REGISTER"}

    def execute(self, context):
        project_root, local_mode = _deduce_project_root(context)
        texture_root = _resolve_texture_root(project_root, local_mode=local_mode)
        manifest_dir = texture_root / "_manifests"

        if not manifest_dir.exists():
            self.report({"INFO"}, "No texture manifest folder found")
            return {"FINISHED"}

        if not manifest_dir.is_dir():
            self.report({"ERROR"}, "Manifest path is not a folder")
            return {"CANCELLED"}

        try:
            shutil.rmtree(str(manifest_dir))
        except Exception as ex:
            self.report({"ERROR"}, f"Failed deleting manifest folder: {ex}")
            return {"CANCELLED"}

        self.report({"INFO"}, "Texture manifest folder deleted")
        try:
            print("[Lime Pipeline] Texture manifest folder deleted:", str(manifest_dir))
        except Exception:
            pass
        return {"FINISHED"}


__all__ = [
    "LIME_OT_texture_manifest_cleanup",
]
