"""
Texture manifest cleanup operator.

Deletes the _manifests folder under the project RSC/Textures directory.
This removes JSON reports and hash index files generated by texture scan/adopt.
"""

from __future__ import annotations

from pathlib import Path
import shutil
from typing import Optional

import bpy
from bpy.types import Operator

from ..core.naming import find_project_root
from ..core.paths import get_ramv_dir


def _deduce_project_root(context) -> Optional[Path]:
    st = getattr(getattr(context, "window_manager", None), "lime_pipeline", None)
    raw = (getattr(st, "project_root", "") or "").strip() if st is not None else ""
    if raw:
        try:
            p = Path(raw)
            if p.exists():
                return p.resolve()
        except Exception:
            pass

    blend_path = (getattr(bpy.data, "filepath", "") or "").strip()
    if blend_path:
        try:
            root = find_project_root(blend_path)
            return root.resolve() if root is not None else None
        except Exception:
            return None
    return None


def _blend_dir() -> Path:
    blend_path = (getattr(bpy.data, "filepath", "") or "").strip()
    if blend_path:
        try:
            return Path(blend_path).resolve().parent
        except Exception:
            return Path(blend_path).parent
    try:
        return Path(bpy.path.abspath("//")).resolve()
    except Exception:
        return Path.cwd()


def _resolve_texture_root(project_root: Optional[Path]) -> Path:
    if project_root is not None:
        try:
            return get_ramv_dir(project_root) / "rsc" / "Textures"
        except Exception:
            pass
    return _blend_dir() / "rsc" / "Textures"


class LIME_OT_texture_manifest_cleanup(Operator):
    bl_idname = "lime.texture_manifest_cleanup"
    bl_label = "Delete Texture Manifests"
    bl_description = "Delete the _manifests folder under RSC/Textures"
    bl_options = {"REGISTER"}

    def execute(self, context):
        project_root = _deduce_project_root(context)
        texture_root = _resolve_texture_root(project_root)
        manifest_dir = texture_root / "_manifests"

        if not manifest_dir.exists():
            self.report({"INFO"}, "No texture manifest folder found")
            return {"FINISHED"}

        if not manifest_dir.is_dir():
            self.report({"ERROR"}, "Manifest path is not a folder")
            return {"CANCELLED"}

        try:
            shutil.rmtree(str(manifest_dir))
        except Exception as ex:
            self.report({"ERROR"}, f"Failed deleting manifest folder: {ex}")
            return {"CANCELLED"}

        self.report({"INFO"}, "Texture manifest folder deleted")
        try:
            print("[Lime Pipeline] Texture manifest folder deleted:", str(manifest_dir))
        except Exception:
            pass
        return {"FINISHED"}


__all__ = [
    "LIME_OT_texture_manifest_cleanup",
]
